### PR TITLE
Update protoc-docs-plugin

### PR DESCRIPTION
**Pull request by busunkim96**
@hzyi-google

### CODE REVIEW

**Comment by busunkim96** [comment]
I'm not sure if the failing test is related to the change:

```You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xgxe2dz6/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-w7d3ru_m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-xgxe2dz6/grpcio/
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c bash install_protoc.sh' returned a non-zero code: 1```

**Comment by hzyi-google** [comment]
Let's try rerunning the test first.

**Comment by busunkim96** [comment]
Bumping the pip version in `install_protoc.sh` seems to have fixed it. PTAL

**Comment by hzyi-google** [comment]
Will release artman shortly - I want to update gapic-generator as well :)

**Pull request merged**
