### PR TITLE
Improve output.

### PR DESCRIPTION
**Pull request by lukesneeringer**
This commit replaces almost all uses of `print` with the `logging` module, and more cleanly separates artman output from the output spit out by the processes that artman runs.

Additionally, it adds a `-v` and `-q` flag to alter how much output you get. Adding `-v` shows all shell commands.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@ethanbao This should make it a bit easier to work on artman; it is the first step toward my GitHub changes. :-) I wanted it to be easier to see what artman is doing.

**Comment by ethanbao** [comment]
This change looks great. One question, artman can also listen to a task queue, fetch task(s) and run tasks in parallel. In addition to the default logger, would it be possible to attach additional stackdriver logger handler for each execution thread, so that each thread will upload the log to cloud with unique log id?

**Comment by lukesneeringer** [comment]
> One question, artman can also listen to a task queue, fetch task(s) and run tasks in parallel.

I have some ideas to how to do this. Will discuss with you later.

**Comment by lukesneeringer** [comment]
@ethanbao has approved in-person. Merging.

**Comment by lukesneeringer** [comment]
I derped and did not see the CI failure. My own fault. Will fix first thing tomorrow morning.

**Comment by ethanbao** [comment]
Oh, I wasn't aware that github will allow merging with CI failure.

**Comment by lukesneeringer** [comment]
It is configurable. We should turn it off. I intend to do that soon on every repo we own.

**Comment by lukesneeringer** [comment]
#154 is the fix. Dumb on me. Feel free to just merge as soon as CI passes.

**Pull request merged**
