### PR TITLE
C# code now generated in directories

### PR DESCRIPTION
**Pull request by chrisdunelm**
Toolkit now generates C# code in the correct directory structure, so all artman now needs to do is copy the proto/gprc generated files into the toolkit-generated directory.

### CODE REVIEW

**Comment by chrisdunelm** [comment]
@ethanbao I'm not very familiar with this repo, and I can't see what's making the "unit-python2.7" CI test fail. Please would you be able to have a look? Thanks.

**Comment by chrisdunelm** [comment]
@geigerj I've just discovered @ethanbao isn't around at the moment. If you'd be able to have a look and help me understand what's making the "unit-python2.7" CI test fail, I'd appreciate it :) Thanks.

**Comment by geigerj** [comment]
@chrisdunelm I'm not sure off the top of my head; I'll take a closer look later. I noticed this failure in https://github.com/googleapis/artman/pull/306, and it appeared to be a flake. Could you try pushing an empty commit to force the test to re-run?

**Comment by chrisdunelm** [comment]
@geigerj  thanks - re-trying now

**Pull request merged**
