### PR TITLE
[chore] Update to new Java resource names invocation.

### PR DESCRIPTION
**Pull request by lukesneeringer**
This uses the new invocation mechanism for the Java resource names plugin.

### CODE REVIEW

**Comment by andreamlin** [comment]
Do tests cover these changes?

**Comment by lukesneeringer** [comment]
> Do tests cover these changes?

The smoke tests should serve as proof (which means something is wrong right now).

**Comment by alexander-fenster** [comment]
@lukesneeringer do we still need this?

**Comment by lukesneeringer** [comment]
I think we can assume this is dead.

**Pull request closed without merging**
