### PR TITLE
Prepare for 0.15.2 release

### PR DESCRIPTION
**Pull request by vchudnov-g**

### CODE REVIEW

**Comment by vchudnov-g** [comment]
Is there anything else I need to do to make this a proper release of artman that will not break anything?

I'm interested in this so I can have the latest toolkit changes in artmanflow. But I don't want to break any other tooling, obviously.

**Comment by andreamlin** [comment]
See go/artman-release-instructions for the rest of artman release
instructions.

The artman circleCI should be ok; it just generates all possible targets
from googleapis. If you haven't changed the surface of gapic-generator,
then I don't see where artman would break...

**Comment by vchudnov-g** [comment]
PTAL @jbolinger @andreamlin

**Comment by jbolinger** [comment]
LGTM @vchudnov-g

**Pull request merged**
