### PR TITLE
Remove update_versions.py script

### PR DESCRIPTION
**Pull request by andreamlin**
We should only be updating the artman Dockerfile version during releases.

~googleapis is pretty much obsolete; that can probably be safely removed.~
gapic-generator hash can be updated manually, and that can be done on an ad-hoc basis.

### CODE REVIEW

**Comment by andreamlin** [comment]
PTAL

@alexander-fenster do you think we still need this update script? At the very least, we should separate out the dependency hash's update from the artman version update.

**Comment by alexander-fenster** [comment]
Yeah, it's probably pretty much useless now.

**Comment by alexander-fenster** [comment]
I just noticed that the contents of this PR and its description don't really match :)

**Comment by andreamlin** [comment]
lol whoops

**Comment by andreamlin** [comment]
PTAL fixed diff

**Pull request merged**
