### PR TITLE
Do not let artman send duplicate protos to protoc.

### PR DESCRIPTION
**Pull request by lukesneeringer**
It turns out `find_protos` can return duplicate results. Good times.
This PR makes us not care about that problem.

@ethanbao Feel free to merge upon reviewing; no need to wait on me.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@ethanbao Is this golden test failure unrelated?

**Comment by ethanbao** [comment]
Michael fixed the golden test failure in another PR.

**Comment by ethanbao** [comment]
I started the rebuild of golden test.

BTW, I was not able to see `artifacts` in the circleci report initially. After I click `user settings` and then connect to Google org, which will require me to login again. After the login, I can see the `artifacts` with current org name at top-left, and my github icon at top-right.

**Comment by lukesneeringer** [comment]
> I started the rebuild of golden test.

Getting a different result would depend on merging master first. :-) (Now done.)

**Pull request merged**
