### PR TITLE
update java resource plugin and bump for release

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by pongad** [comment]
Let's not merge this yet. We should also update toolkit.

**Comment by jadekler** [comment]
> Let's not merge this yet. We should also update toolkit.

Any idea of an ETA?

**Comment by pongad** [comment]
@jadekler I hope to merge this in order or days.

**Comment by lukesneeringer** [comment]
Node seems to fail to build again. Looking into it. Argh.

**Comment by lukesneeringer** [comment]
@andreamlin Good catch.

**Comment by lukesneeringer** [comment]
This can be merged after the tests (eventually) pass. Then it is a PyPI release and Docker upload, in that order.

**Pull request merged**
