### PR TITLE
Update gapic-generator hash and Java resource name plugin

### PR DESCRIPTION
**Pull request by hzyi-google**
gapic-generator:
- feat: add the last segment when generating names for singleton resoures
- fix: add null check and better error message when referenced resources are not found
- feat: Support extra plugin_args for php bazel rules rules (#3165)
- feat: support '*' in resource definition (#3163)
- fix: align text in license (#3158)
- fix(python): add PROJECT_ID for python-system-test (#3161)
- fix(PYTHON): update nox file and modernize to new interface (#3156)

resource name plugin
- feat: add the last segment when generating names for singleton resources
- feat: support * annotation in resource def (#84) 
- feat: trace up only one level when calculating parent types with singleton resources
- fix: stop generating `parseList` and `toStringList` if a multi-pattern resource class has subclasses

also whitelist Asset to unblock releasing artman.

### CODE REVIEW

**Comment by hzyi-google** [comment]
_Looking at golden test..._

**Comment by alexander-fenster** [comment]
Golden test is basically just a list of filenames that gets compared to the output. Seems like Python has changed `noxfile.py` to `nox.py`? It's in https://github.com/googleapis/gapic-generator/pull/3156.

**Comment by hzyi-google** [comment]
@alexander-fenster done!

**Comment by alexander-fenster** [comment]
Isn't it cool to release artman in your last day in the team @hzyi-google ? :)

**Comment by hzyi-google** [comment]
Hahaha and I even looked into the golden test directory for the first time :)

**Pull request merged**
