### PR TITLE
Bump dependencies, version to 0.8.1

### PR DESCRIPTION
**Pull request by lukesneeringer**

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Marking `do not merge` until after I/O. Safe to merge next week.

**Comment by lukesneeringer** [comment]
Note: This seems to have a failure in Node.

**Comment by garrettjonesgoogle** [comment]
Merge now?

**Comment by pongad** [comment]
@lukesneeringer It seems like we're trying to do the same thing. I also sent PR to update [here](https://github.com/googleapis/artman/pull/417). Shall I close that in favor of this one?

**Comment by lukesneeringer** [comment]
Actually let's go with yours, which is now the up to date one.

**Pull request closed without merging**
