### PR TITLE
NodeJS: Copy .proto files on gapic generation

### PR DESCRIPTION
**Pull request by eoogbe**

### CODE REVIEW

**Comment by eoogbe** [comment]
Where is the artifacts section of the circleci report?

**Comment by ethanbao** [comment]
I am confused how circleci artifacts work, as I don't see consistent report in my experience.

Since your change is simple, the error report is good enough, and you only need to add one line into library_example.golden.
"
>       assert expected == set(actual), \
            "Check the actual output at %s" % actual_output_file
E       AssertionError: Check the actual output at /usr/src/artman/test/golden/actual_library_example.golden
E       assert {'/csharp/goo...Grpc.cs', ...} == {'/csharp/goog...Grpc.cs', ...}
E         Extra items in the right set:
E         '/js/library_example-v1/proto/google/example/library/v1/library.proto'
E         Use -v to get the full diff
"

**Comment by lukesneeringer** [comment]
> @ethanbao Where is the artifacts section of the circleci report?

screen_shot_2017-09-11_at_8_30_08_am

**Comment by eoogbe** [comment]
image

**Pull request merged**
