### PR TITLE
Update PHP protoc generation

### PR DESCRIPTION
**Pull request by michaelbausor**
Move PHP off packman, and start using protoc directly from artman

### CODE REVIEW

**Comment by ethanbao** [comment]
The php smoketest is failing though the circleci report page stales. Does this change require change to Dockerfile?

**Comment by michaelbausor** [comment]
Yes, it does. I am working through changes to the Dockerfile now - I will update the PR once I have the smoke test passing.

**Comment by ethanbao** [comment]
Due to this issue (https://github.com/googleapis/artman/issues/223), the circleci-based smoke test will still fail. You can follow the instruction in contributing.rst to smoke test your change locally. Once you confirm the php test passed, I will temporary disable the smoke-php test so that you can merge the PR, and I will re-enable the test once the new artman docker image is released to docker hub.

**Comment by geigerj** [comment]
cc: @geigerj

(I'd like to be notified with this is approved so that I can begin cleaning up dead packman code.)

**Comment by michaelbausor** [comment]
@ethanbao I have updated the dockerfile and tested that the smoke test passes locally.

I have not updated the toolkit version in the Dockerfile, because I would like to include two outstanding toolkit PRs: https://github.com/googleapis/toolkit/pull/1390 and https://github.com/googleapis/toolkit/pull/1389

Once those are merged, is the process simply to update the Dockerfile, or are there other steps I need to take? And, should I wait to include any other pending toolkit changes for other languages?

**Comment by geigerj** [comment]
@michaelbausor @ethanbao Any progress here?

**Comment by michaelbausor** [comment]
@geigerj I have just now merged the relevant toolkit PRs. I will update this PR once I have tested locally and confirmed that smoke tests are still passing.

**Comment by ethanbao** [comment]
@michaelbausor You don't need to wait for other toolkit changes, unless your toolkit PRs are relying on other toolkit change. You can update toolkit commit hash inside Dockerfile in this PR, even though our CI testing will keep failing.

I have disabled the smoke-php test, so your PR can merge even if the test is failing.

**Comment by michaelbausor** [comment]
I have updated with the required toolkit version, PTAL. Smoke test is passing locally.

**Pull request merged**
