### PR TITLE
Redirect from old gapi-tools to new Github toolkit repo

### PR DESCRIPTION
**Pull request by bjwatson**
Pre-push hook installed.

Change-Id: I9ac46c3a2157ea20718617568aae459e58ee1a88

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Update USAGE.rst also.

**Comment by bjwatson** [comment]
There's no reference to 'gapi' or 'tools' in that file

**Comment by garrettjonesgoogle** [comment]
oh, right. ok!

**Comment by ethanbao** [comment]
Can you squash the commits into one?

**Comment by bjwatson** [comment]
@ethanbao Done.

**Comment by ethanbao** [comment]
LGTM

**Pull request merged**
