### PR TITLE
Update docker image

### PR DESCRIPTION
**Pull request by geigerj**
Previous image incompatible with `config_schema_version` in GAPIC yaml

### CODE REVIEW

**Comment by andreamlin** [comment]
There is a newer docker image googleapis/artman:0.5.0-rc03. Why isn't that one hardcoded in?

**Comment by geigerj** [comment]
@andreamlin I think it was just that @ethanbao hadn't released that image yet at the time I created this PR. @ethanbao Can we update this hardcoded value as part of the docker image release process?

**Comment by ethanbao** [comment]
It is possible. We actually have a release doc, I need to figure out a way to enforce that.

**Comment by ethanbao** [comment]
OTOH, any problem with using 0.5.0-rc02 for now, @andreamlin? There is no guarantee that the latest pushed docker image will be marked as the one used in artman.

**Pull request merged**
