### PR TITLE
Rename veneer_yaml arg to gapic_yaml

### PR DESCRIPTION
**Pull request by chrisdunelm**

### CODE REVIEW

**Comment by bjwatson** [comment]
Thanks @chrisdunelm. Can you also fix similar issues in test/testdata/?

**Comment by chrisdunelm** [comment]
test/testdata/ files also updated, PTAL

**Comment by chrisdunelm** [comment]
OK, never mind, I see that PR#10 has already done all this.

**Comment by bjwatson** [comment]
Oh, sorry @chrisdunelm. I forgot to circle back on you regarding that. I did a global veneer -> gapic replace in the the toolkit repo a couple days ago, so did the same yesterday for artman.

**Pull request closed without merging**
